### ISSUE TITLE
Bug: layer ordering

### ISSUE THREAD

**Issue by jkarttunen** [design-meets-development/design-tokens-plugin#7]
The layer named 'design-tokens' needs to be first in order to export to work. 

This fails:
<img width="241" alt="Screenshot 2020-03-18 at 8 08 51" src="https://user-images.githubusercontent.com/914822/76930802-01365880-68f0-11ea-9e84-d584ced46ba9.png">

This works in the same file
<img width="233" alt="Screenshot 2020-03-18 at 8 11 37" src="https://user-images.githubusercontent.com/914822/76930869-25923500-68f0-11ea-92c6-fe42989d97db.png">

**Comment by vjandrei** [comment]
Good found, I need to investigate this problem. 
I think this is the issue here. 

`const designSystemExport = () => {
  // Check here if even one file is found and something can be exported
  sketchDom.getSelectedDocument().pages[0].name;
  if (sketchDom.getSelectedDocument().pages[0].name === "design-tokens") {
    const userExportOptions = sketchExportModal();
    saveFileModal(userExportOptions.fileformat);
  } else {
    UI.alert("Error 🛑", 'No tokens page found!\r\nMake sure that page name is "design-tokens"!');
  }
};`

It will take the first array on the pages list.

**Comment by vjandrei** [comment]
The idea for this tokens library was to be isolated file without any other pages.
But I think there is needs to use the library in any way.

**Comment by vjandrei** [comment]
It is now fixed and tested. So there is only filter now that looks "design-tokens" page any on the pages array.
